name: todo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #======= native splash =======#
  flutter_native_splash: ^2.4.1
  #====== bloc =====#
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  #======= git it for no create new object ===///
  get_it: ^7.6.0
  injectable:
  # ===== server ====#
  dio: ^5.7.0
  pretty_dio_logger: ^1.3.1
  equatable: ^2.0.5
  dartz: ^0.10.1

  #===== image =====#
  cached_network_image: ^3.3.1
  skeletonizer: ^1.4.2
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  #===== local data base ========#
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.2.2
  #====== responsive screen=========#
  flutter_screenutil: ^5.9.3
  #======== note =======#
  fluttertoast: ^8.2.2
  #======= no internet =========#
  flutter_offline: ^4.0.0
  #============== loading ====///
  flutter_spinkit: ^5.2.1
  #==== check phone ====#
  phone_numbers_parser: ^8.2.1
  #====== get country ====#
  country_code_picker: ^3.0.0
  #====== otted borders around widgets ======#
  dotted_border: ^2.1.0
  #======= date ========#
  intl:
  #========= qr code =========#
  mobile_scanner: ^6.0.2
  qr_flutter: ^4.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:


  flutter_lints: ^4.0.0
  build_runner: ^2.4.11

flutter:


  uses-material-design: true
  assets:
    - lib/core/global/images/
    - lib/core/global/icons/
